---
title: "feature_lyq"
author: "Yaqin Li (yl3578)"
date: "4/24/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


##Input and packages

```{r}
train <- read.csv("../data/train.csv", header = T, as.is = T)
Q1<-train[1:50000,4]
Q2<-train[1:50000,5]
label<-train[1:50000,5]

library(tm)
library(qdap)
library(plyr)
#install.packages("tm.lexicon.GeneralInquirer", repos="http://datacube.wu.ac.at", type="source")
library(tm.lexicon.GeneralInquirer)
#library(devtools)
#install_github("mannau/tm.plugin.sentiment")
library(tm.plugin.sentiment)

Q1.doc<-Corpus(VectorSource(Q1))
Q2.doc<-Corpus(VectorSource(Q2))
```

##Transform and word count

```{r}
Q1.doc<-tm_map(Q1.doc,content_transformer(tolower))
Q2.doc<-tm_map(Q2.doc,content_transformer(tolower))

text.count<-function(sent){
  text<-sent[[1]]
  punc<-length(gregexpr("[.|!|?|;|:|,]",text)[[1]])
  modal<-length(gregexpr("will|can|shall|must|should|would|could|may|might",text)[[1]])
  neg<-length(gregexpr("never|not|non|rare|no|neither|seldom|hardly",text)[[1]])
  word<-strsplit(text," ")
  return(list(punc=punc,modal=modal,neg=neg,word=length(word[[1]])))
}



Q1.num<-llply(Q1.doc,text.count)
Q1.num<-ldply(Q1.num,unlist)

Q2.num<-llply(Q2.doc,text.count)
Q2.num<-ldply(Q2.num,unlist)

```




##Sentiment analysis
```{r}
pos.score <- tm_term_score(TermDocumentMatrix(Q1.doc, control = list(removePunctuation = TRUE)), 
                           terms_in_General_Inquirer_categories("Positiv")) 

neg.score <- tm_term_score(TermDocumentMatrix(Q1.doc, control = list(removePunctuation = TRUE)), 
                           terms_in_General_Inquirer_categories("Negativ")) 

Q1.sentiment <- data.frame(positive = pos.score, negative = neg.score)
Q1.sentiment <- transform(Q1.sentiment, net = positive - negative)

pos.score <- tm_term_score(TermDocumentMatrix(Q2.doc, control = list(removePunctuation = TRUE)), 
                           terms_in_General_Inquirer_categories("Positiv")) 

neg.score <- tm_term_score(TermDocumentMatrix(Q2.doc, control = list(removePunctuation = TRUE)), 
                           terms_in_General_Inquirer_categories("Negativ")) 

Q2.sentiment <- data.frame(positive = pos.score, negative = neg.score)
Q2.sentiment <- transform(Q2.sentiment, net = positive - negative)
```


##feature extraction

```{r}
feature<-data.frame()
```



